# Generated by Django 5.0.4 on 2026-05-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('hydro', 'Hydro'), ('biomass', 'Biomass'), ('geothermal', 'Geothermal')], max_length=20)),
                ('capacity_kw', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('installation_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Energy Source',
                'verbose_name_plural': 'Energy Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('output_kwh', models.FloatField()),
                ('efficiency_percent', models.FloatField(default=0.0)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('solar_irradiance', models.FloatField(blank=True, null=True)),
                ('co2_saved_kg', models.FloatField(default=0.0)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.energysource')),
            ],
            options={
                'verbose_name': 'Energy Reading',
                'verbose_name_plural': 'Energy Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
